--流程配置表
create table WF_TASK_CONFIG(
  CONFIG_ID VARCHAR (32) NOT NULL PRIMARY KEY ,
  PROCESS_DEF_KEY VARCHAR (50) NOT NULL ,
  TASK_DEF_KEY VARCHAR (50) NOT NULL ,
  TASK_TYPE CHAR(1) NOT NULL ,
  TASK_CONFIG VARCHAR (255),
  IS_EDIT CHAR(1)
);

COMMENT ON TABLE WF_TASK_CONFIG IS '流程配置表';

COMMENT ON TABLE WF_TASK_CONFIG.CONFIG_ID IS '主键';
COMMENT ON TABLE WF_TASK_CONFIG.PROCESS_DEF_KEY IS '流程定义的key';
COMMENT ON TABLE WF_TASK_CONFIG.TASK_DEF_KEY IS '环节定义的key';
COMMENT ON TABLE WF_TASK_CONFIG.TASK_CONFIG IS '环节配置';
COMMENT ON TABLE WF_TASK_CONFIG.TASK_TYPE IS '0/1 O代表起草环节 1代表其它环节 2代表结束节点';
COMMENT ON TABLE WF_TASK_CONFIG.IS_EDIT IS '0不可编辑 1代表可编辑';

